### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/grid-engine#132] opened 2021-05-22 06:44 UTC
Image attached below
![image](https://user-images.githubusercontent.com/49586102/119217346-4f418000-bae2-11eb-9b8b-744881d2fd55.png)

**Comment by Annoraaq** [comment] 2021-05-24 12:33
Can you provide any context information? Which call causes this? How do you initialize/configure the plugin. Have you made sure, you are passing the correct data types to the plugin?

I'm not able to reproduce the error without any further information.

**Comment by borkowsky** [comment] 2021-05-24 16:24
> Can you provide any context information? Which call causes this? How do you initialize/configure the plugin. Have you made sure, you are passing the correct data types to the plugin?
> 
> I'm not able to reproduce the error without any further information.

When i move player to any direction this error appear in console

**Comment by Annoraaq** [comment] 2021-05-25 18:18
I fear I still can't reproduce this. Which version are you using and how are you setting up the plugin? Can you maybe provide a minimum breaking example?

**Comment by borkowsky** [comment] 2021-06-15 04:20
Sorry for late answer, i provide code soon. Very busy (

**Comment by splashsky** [comment] 2021-06-25 21:02
@borkowsky Any updates? If not I'll close this case on Monday.

**Comment by Annoraaq** [comment] 2021-07-10 15:23
I will close this for now.

**Closed by Annoraaq** 2021-07-10 15:23 UTC
