### ISSUE TITLE
Collision detection shifted when diagonal movement is enabled

### ISSUE THREAD

**Issue by KaeruCT** [Annoraaq/grid-engine#257] opened 2022-03-26 20:33 UTC
Hi! Thanks for your work on this plugin. I'm having a great time building my game with it.

I found an issue when diagonal movement is enabled. I was able to reproduce this on [one of the demos](https://annoraaq.github.io/grid-engine/examples/8-directions-move-to.html) in the documentation site.

To trigger this bug, find something you can easily walk around. I used one of the statues in the cloud city map. You need to move diagonally a lot around the solid tiles. Try to avoid having the character do any non-diagonal movements. Eventually something messes up and the character will start going through those tiles (around 00:10 in the video). If you keep moving around, you will notice the collision seems to have shifted by several tiles. I try to show this in the video by walking around where the statue seems to be. I'm not sure if this always happens in the same direction.

https://user-images.githubusercontent.com/1018253/160255914-5c124b85-d932-4660-ac1c-e9e96e688a0f.mp4

**Comment by Annoraaq** [comment] 2022-03-28 18:19
Thanks for sharing! I will take a look at this. 👍

**Comment by Annoraaq** [comment] 2022-03-29 17:21
I can't reproduce this issue. I've tried a lot in Chrome and Safari. It might be related to #224, which I also could not reproduce.

@Mteuahasan, since you were having a similar issue, can you reproduce this on the [example](https://annoraaq.github.io/grid-engine/examples/8-directions-move-to.html)?

**Comment by KaeruCT** [comment] 2022-05-19 05:41
@Annoraaq sorry for the late reply. This happens to me both in latest versions of Chrome and Firefox on Windows 10.
One way I found it happens more often is to increase the moving speed to something really fast: 

```js
this.gridEngine.setSpeed("player", 20);
```

**Comment by Annoraaq** [comment] 2022-05-19 18:54
Hey @KaeruCT,

I tried to reproduce it with high speed in MacOs Chrome and with normal speed on a Windows 10 machine but still could not reproduce it within 30 minutes. I assume there is some missing factor that triggers it.

**Comment by ok1a** [comment] 2023-02-24 04:35
Hey @KaeruCT , did you ever resolve this? I'm experiencing the same thing now, out of nowhere -- on a project I've ben using this package on for over a year now.

Wondering what happened...

**Comment by Annoraaq** [comment] 2023-02-24 11:18
@ok1a Do you also experience it on the example of the website or only in your own project?

**Comment by ok1a** [comment] 2023-02-24 14:10
@Annoraaq Nothing on the example of the website. Only tried for 10 minutes. Will try for an additional 10 minutes to recreate on the example.

I can invite you to our production deployment if you would like to try experiencing the bug yourself there. Please send me a place I can DM or eMail you so I can send you connection steps (whitelisted server access).

I only noticed it happening last night on local -- but turns out it's been happening for at least the past 3 days, since that was last merge to prod and I can experience the issue there.

I will continue debugging myself as this is critical for my needs. I will report back any findings.

**Comment by KaeruCT** [comment] 2023-02-24 14:22
> Hey @KaeruCT , did you ever resolve this? I'm experiencing the same thing now, out of nowhere -- on a project I've ben using this package on for over a year now.
> 
> Wondering what happened...

@ok1a Sorry, I was never able to resolve this. I ended up not using diagonal movement as it was not critical for my game.
I do hope we manage to get to the bottom of this bug!

**Comment by ok1a** [comment] 2023-02-24 15:49
This isn't a diagonal movement thing. It's got to be an NPC movement bug in potential combination with tilemap settings.

I turned off diagonal movement -- now my own character no longer experiences the bug where I can clip through things etc etc, but I can still re-create and try walking through NPCs. The NPCs still do eventually become.. like... their sprite will be in pos X1 Y1 but their collision box will be in X0Y1, so when I walk in X1Y1 I can go through their sprite but if I go through X0Y0, a blank space, I collide.

**Comment by ok1a** [comment] 2023-02-24 15:51
Is there anything in the .moveTo or .moveRandomly or move Radius code that could be causing a conflict with pathfinding when path is blocked by other NPC/sprite/grid object, that could be pushing a character/NPC/sprite/grid object into another collision layer? @Annoraaq 

The only thing I did differently in the past few weeks was add a character and set him to move via Radius. I only noticed this bug yesterday, when I added 4 more characters who should move within a radius.

**Comment by Annoraaq** [comment] 2023-02-24 17:48
@ok1a the simplest way for DM is probably our discord server: https://discord.gg/C4jNEZJECs

@ok1a from what you are describing, it could be a bug with the so called `CharBlockCache`. It is a data structure that is used to efficiently determine which character is blocking **on a specific position**. Without it, for each collision check all characters would have to be checked, which can be a significant performance issue if we have many characters.

However, there might be a bug that leads to a de-sync of the cache and the char positions.

I will also investigate. Let me know if you find a minimal example for reproducing this.

**Comment by Annoraaq** [comment] 2023-02-24 17:53
I forgot to ask: is there a specific reason why you are not using the latest version of GridEngine? Anything that stopped working, or did you simply not update it yet?

**Comment by ok1a** [comment] 2023-02-24 17:59
Hey, shot you a DM on discord. I'll try stashing, un-pinning version, and attempt reproducing.

**Comment by ok1a** [comment] 2023-02-25 19:53
Commenting to say that this has been resolved for me. An update to the latest version of grid-engine fixed whatever I was experiencing (for diagonal, regular, all movement etc)

**Comment by KaeruCT** [comment] 2023-02-27 11:31
@Annoraaq I updated `grid-engine` in my project to the latest version and I cannot reproduce this issue anymore. :)

**Comment by Annoraaq** [comment] 2023-02-27 17:19
Thanks for checking @KaeruCT! Very nice to head that it disappeared. It seems that I accidentally fixed it 😄 

I will close this bug for now.

**Closed by Annoraaq** 2023-02-27 17:19 UTC
Labels: bug
