### ISSUE TITLE
Creating a follower after using `setPosition` lags the world

### ISSUE THREAD

**Issue by ok1a** [Annoraaq/grid-engine#274] opened 2022-04-14 12:18 UTC
Hi.

I've currently got followers added in my game world. Followers can be added and removed with no problem.

However, when I attempt to use `setPosition` before spawning a follower -- everything functions well until said follower is spawned in. When the follower is spawned in, the world begins to lag uncontrollably. 

Here is the bug in action:
https://www.loom.com/share/5a49744b121d44fcad0f423ae0e7baaa
I attempted to show you the bug occurring after spawning a follower and then using `setPosition`, as well as using `setPosition` prior to any follower spawning.

Note that my follower creation code is simply adding a character and using `.follow()`. Remove is a bit more complicated than that, but the bug occurs prior to removing a follower.

This video also displays the bug occurring in #273.

**Comment by zewa666** [comment] 2022-04-14 13:03
@ok1a setPosition takes an optional 3rd param being the layer. have you tried setting that?

**Comment by ok1a** [comment] 2022-04-14 13:06
@zewa666 Wow. I have no idea how I missed that.
Seems like that fixed my issues in both #273 and #274, so I'll close these.

I understand it fixing #273, but I'm surprised it fixed #274.

Thanks a lot!

**Comment by Annoraaq** [comment] 2022-04-26 18:49
Maybe there is some bug in `follow()` that makes it slow whenever the character to be followed is on an unreachable char layer. I will check that out. Thanks for letting us know 👍

**Comment by Annoraaq** [comment] 2022-04-26 19:21
I could not replicate it. But there are some missing pieces such as:

- How many characters do you have?
- Who is following whom?
- Which parameters are you using for follow?
- Where in your code are you calling it exactly?
- On which character are you calling setPosition?
- How many char layers do you have and on which layers are the characters?
- How large is your map?
- ...

So the best thing would be a minimum breaking example. But since it is working now, I think it is not worth the effort 😁

**Comment by ok1a** [comment] 2022-04-26 22:01
Replying because although the above was fixed by specifying the layer when using `setPosition`, I am experiencing a new bug: Creating a character and having them follow me (the WASD moving player)... it works well, until the follower has their path trapped. If follower has path trapped, and cannot proceed, the world will begin to lag after I myself have made 10-30 movements away from the follower. Prior to 10-30 movements, the world is okay. Seems like the path computation must be really expensive and ever growing as I continue to move farther away into the world.

* 10-30 characters on the map. Problem exists when there are only two characters, as well as 10-30.
* I create a new character NPC, and I have them follow me, the character I control movement of.
* Presently, I use all of the parameters. myId, theirId, charLayer.
* I have a subscription for the createFollower command. On command, we create a new character and call setFollow.
* I have 16 layers on my main map. Of that, I have 1 charLayer.
* My map is 120x120 32px tiles.

**Comment by Annoraaq** [comment] 2022-04-27 19:34
What parameters do you use for the `follow()` call?

Can you elaborate more on what you mean by "path trapped"?

**Comment by ok1a** [comment] 2022-04-27 20:14
For `follow()`, I use the same parameters as I listed prior above.

`this.gridEngine.follow(followerId, playerId, 0);`.
I have verified that this also occurs when using:
`this.gridEngine.follow(followerId, playerId, 0, true);`.

Path blocked/trapped is referring to being stuck behind a collision tile.
I've included a demo below for clarity.
https://www.loom.com/share/f0312f2b88994f52a961c2a87d6dcc05

**Comment by Annoraaq** [comment] 2022-04-28 16:51
Thanks, I can reproduce this now on a large map 👍 . I will come back with updates.

**Comment by ok1a** [comment] 2022-04-28 16:58
I was thinking of handling this locally, in the meantime, by setting a subscription to follower movements and determining the delta between playerPos and followerPos. If the delta was something like +5 or +10 tiles away, I would despawn the follower.

**Comment by Annoraaq** [comment] 2022-05-01 15:35
I checked it out and indeed the pathfinding is the bottleneck. I was able to optimize it a bit by using bidirectional search instead of BFS (#85). Moreover there were some further optimizations. However, while making it much faster there is still a lag. I think the best optimization is to use [Jump Point Search](https://zerowidth.com/2013/a-visual-explanation-of-jump-point-search.html). I created #277 for this.

**Comment by TorbenTK** [comment] 2023-01-30 09:12
I've run into the same thing as described here with v2.24, though my conditions are a little different (using 1 NPC only):

1. I assign the NPC to follow the player using `.follow()`
2. I call `.stopMovement()` for the NPC so it will no longer follow.
3. I may call `.follow()` afterwards to again follow the player

Weirdly enough, I get the lag when my NPC has **stopped** following and when I'm moving away from it. The lag increases the more distance I create between player and NPC. I wouldn't expect this as the NPC no longer needs to follow.

Does grid-engine keep trying to calculate a path continuously if I once assigned `follow()` to a game object, even though it doesn't need to follow anymore? If so, can I (somehow) remove the follow assignment entirely?

**Comment by Annoraaq** [comment] 2023-01-30 18:13
That does at least partially sound like a bug to me and not only a performance issue, because after `stopMovement()` there should not happen any pathfinding anymore.

I will investigate.
How large is the map and the typical distance at which you start observing the lag?

**Comment by Annoraaq** [comment] 2023-01-30 18:44
I can confirm that there is a bug that causes the pathfinding to continue, even after calling `stopMovement()`. I am already working on a fix. However, it will not solve the performance issue you described.

The number of obstacles should not make too much of a difference, because the algorithm that is used (Bidirectional search) is kind of a BFS from start and end at the same time. That means it does not use a heuristic, like A* does. But A* is slower than bidirectional search in general. But bidirectional search can't be used in graphs with weights.
So using A* would also not solve the issue because it would optimize for best case scenarios with little obstacles, but make it worse for scenarios with many obstacles.

That means it would be interesting to know whether the performance issues you observe are caused by the limits of bidirectional search, or if there is a bug in the algorithm's implementation (or elsewhere).
That is why I am interested in the size of the map.

**Comment by Annoraaq** [comment] 2023-02-02 17:02
Thanks for all the details. I will take a closer look.

The problem with the ongoing pathfinding after calling `stopMovement` should be fixed with the just released version 2.25.1.

**Comment by Annoraaq** [comment] 2023-02-02 17:40
Actually, the fix could already fix your problem. The observables were not properly unsubscribed on `stopMovement`. So for every time you call `stopMovement` and start a new follow movement, there will be one pathfinding on each position change of the player (6 times per second in your case). That means if you stopped and started the `follow` movement `n` times. There will be n*6 pathfinding runs each second. Depending on the size of `n` this can make the game unplayable.

So let me know if the performance issues got better, because the scenario you described (map size etc) should easily be handled by the algorithm.

**Comment by TorbenTK** [comment] 2023-02-04 11:20
That makes sense, thanks for the explanation.

I've tested it and I no longer experience a drop in performance. The fix seems to have done the trick. 👍

**Comment by Annoraaq** [comment] 2023-02-04 16:08
Nice to hear. It should get more performant in the future with further optimizations.

**Comment by Annoraaq** [comment] 2023-04-22 17:21
@ok1a Is this still an issue? The above mentioned bug with `stopMovement` could already solve that issue.

There will still be pathfinding performance optimizations in the next release. However, if the above bugfix already solved it, we can close this issue already.

**Closed** 2023-06-06 17:11 UTC
Labels: bug, performance
